name: Django Project CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Instalar Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Revision con flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Subir zip del proyecto
        uses: actions/upload-artifact@v2
        with:
          name: proyecto-aduana
          path: ~/aduana/
